export { parseFmc } from './fmc'
export { Color } from './color'
export { escapeSpecialChar } from './unicode-helper'
export { RichSpan } from './span'
export { RichString } from './str'
export { DecorationType,Decorations } from './decoration'